---
- hosts: all
  vars:
    sshkey: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  tasks:
    - name: Make sure apt-get is up to date
      apt: update_cache=yes
    - name: Upgrade Packages
      apt: upgrade=dist
    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      sudo: true
      ignore_errors: true
    - name: waiting for server to come back
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          state=started
          delay=30
          timeout=300
      sudo: false
    - name: Push SSH key to server
      lineinfile: dest=/root/.ssh/authorized_keys state=present line="{{sshkey}}"
      #authorized_key: user=root  key=sshkey
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh
    - apt: name={{item}} state=present
      with_items:
      - vim
      - tmux
      - htop
      - ntp
      - ntpdate
    - name: Configure ntp
      copy: src=ntp.conf dest=/etc/ntp.conf
            owner=root group=root mode=0644
      notify: Restart ntp
    - name: Fix time before we start ntp service
      command: ntpdate -u pool.ntp.org
      changed_when: False
    - name: Enable ntp service
      service: name=ntp enabled=yes
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
    - name: Restart ntp
      service: name=ntp state=restarted
